var game = new Phaser.Game(1500, 1000, Phaser.AUTO);
game.state.add('story', demo.story);
game.state.add('mg_hunting', demo.mg_hunting);
game.state.add('mg_fishing', demo.mg_fishing);
game.state.add('mg_gathering', demo.mg_gathering);
game.state.add('title_screen', demo.title_screen);
game.state.add('tutorial_hunting', demo.tutorial_hunting);
game.state.add('tutorial_fishing', demo.tutorial_fishing);
game.state.add('tutorial_gathering', demo.tutorial_gathering);
game.state.add('tutorial_backstory', demo.tutorial_backstory);
game.state.add('tutorial_gameplay', demo.tutorial_gameplay);
game.state.add('tutorial_goal', demo.tutorial_goal);
game.state.add('tutorial_logging', demo.tutorial_logging);
game.state.add('resources_needed', demo.resources_needed);
game.state.add('minigame_selection_page', demo.minigame_selection_page);
game.state.add('mg_logging', demo.mg_logging);
game.state.add('day_recap', demo.day_recap);
game.state.add('game_over', demo.game_over);
game.state.start('title_screen');